#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH -t 8:00:00
#SBATCH -J trinity_11
#SBATCH --mail-type=ALL
#SBATCH --mail-user ho-yeung.chim.2766@student.uu.se

# Load modules
module load bioinfo-tools
module load trinity

cd /proj/genomeanalysis2022/nobackup/work/hychim/sorted/

for file in ./*
do
	Trinity \
	--genome_guided_bam ${file} \
	--CPU 16 \
	--max_memory 500G \
	--genome_guided_max_intron 10000 \
	--output /proj/genomeanalysis2022/nobackup/work/hychim/trinity/${file}_trinity
done
